using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Sample.Console.Models
{
    public class RB_Customer_Setting
    {
        public int CustomerID { get; set; }
        public int BuyerAssignType { get; set; }

        public int DefaultWareHouseID { get; set; }

        public bool CheckOrderBlackList { get; set; }

        public bool CheckOrderProfit { get; set; }

        public decimal ShipFeePerG { get; set; }

        public string BeginSetStep { get; set; }

        public string CheckAndPut { get; set; }

        public string BuyAndCheck { get; set; }

        public string IsHiddenB2CFunction { get; set; }

        public string HideAmazonProductUpload { get; set; }
        public string HideEbayProductUpload { get; set; }
        public string isUploadToBrand { get; set; }
        public decimal ProfitMargin { get; set; }

        public string CarriagePrice { get; set; }
        public string BuiltOrderAudit { get; set; }
        public string DefaultBuyerType { get; set; }
        public string StoreAgeDay { get; set; }
        public string SoldOutDay { get; set; }
        public string AmazonStoreAgeDay { get; set; }
        public string AmazonSoldOutDay { get; set; }
        public string IsUseCustomerExchangeRMB { get; set; }
        public string IsProcurementBuildDK { get; set; }
        public string IsProcurementBuild { get; set; }
        public string IsOrderDistribution { get; set; }
        public string IsAllDelivering { get; set; }
        public string IsAutoCreateOrder { get; set; }
        public string PaymentPwd { get; set; }
        public string IsEbayAutoReplenish { get; set; }
        public string IsAutoRemoveStorage { get; set; }
        public string IsNewMailAndReviewOrder { get; set; }
        public string IsProcurementBackDefault { get; set; }
        public string IsProductionToProcurementByOrder { get; set; }
        public string IsProductionToProcurementByStockOrder { get; set; }
        public string IsCheckBuyNum { get; set; }
        public string IsOverStockToAPI { get; set; }
        public string IsAmazonListBuild { get; set; }
        public string IsEbayListBuild { get; set; }
        public string IsStockingListBuild { get; set; }
        public string ExceptionSKUs { get; set; }
        public string CustomsCost { get; set; }
        public string IsBuildRawMaterialPackage { get; set; }
        public string IsLimitBatchNoByBarCode { get; set; }
        public string IsWeighByBarCode { get; set; }
        public string PickingTypeByBarCode { get; set; }
        public string IsUseTally { get; set; }
        public string IsOpenEFN { get; set; }
        public string IsProcurementBuildByPurchaser { get; set; }
        public string IsSupplierMustAuditPass { get; set; }
        public string IsOverweightMerge { get; set; }
        public string SmsNotificationTels { get; set; }
        public string IsAutoCleanAmazonListing { get; set; }
        public string IsSafetyStock { get; set; }
        public string IsScanPositCode { get; set; }
        public string IsEnabledProductDiscontinuedApprove { get; set; }
        public string ProductDiscontinuedApproveDay { get; set; }
        public string ProductDiscontinuedApproveSales { get; set; }
        public string ProcurementGuid { get; set; }
        public string FirstLegAssignType { get; set; }
        public string SellerSeal { get; set; }
        public string BuyerSeal { get; set; }
        public string IsScannAllProductPrint { get; set; }
        public string DefaultCheckType { get; set; }
        public string IsEFNSeparateStocking { get; set; }
        public string RefundSeal { get; set; }
        public string GeneralSeal { get; set; }
        public string IsBarCodeConfig { get; set; }
        public string Intelligent { get; set; }
        public string IsShowMoney { get; set; }
        public string LlLoignPwd { get; set; }
        public string SortRule { get; set; }
        public string StockupEstimated { get; set; }
        public string IsSortWeight { get; set; }
        public string IsBatchPrint { get; set; }
        public string IsSplitOrderByFBA { get; set; }
        public string ShowOneOrTwo { get; set; }
        public string BuyNumberSetting { get; set; }
        public string IsSystemAutoStrike { get; set; }
        public string AllowPurchasingDepartmentToCallBack { get; set; }
        public string IsAKeyOffline { get; set; }
        public string IsOverStockListBuild { get; set; }
        public string IsEnableNewEditionEbayListingService { get; set; }
        public string IsCloseOldEditionEbayListingService { get; set; }
        public string IsPrintOrderBookShowImage { get; set; }
        public string IsNoPurchaserForProductionPurchaseOrder { get; set; }
        public int SetTheMaximumNumberOfPackages { get; set; }
        public string IsNewSupplierManagementEnabled { get; set; }
        public string IsFinancialAuditEnabled { get; set; }
        public string IsHideNoPermissionMenu { get; set; }
        public string IsSupportContinueSinglePin { get; set; }
        public string SalesCostAccountDay { get; set; }
        public string ManualStorageSystemSKU { get; set; }
        public string IsPaymentTestTransactionNumber { get; set; }
        public string EbayPriceLimitType { get; set; }
        public string EbayPricePercentage { get; set; }
        public string IsBombBoxHints { get; set; }
        public string PriceRatioOfCustomsClearance { get; set; }
        public string IsOpenNewInventoryManagement { get; set; }
        public string IsEnable1688PlaceOrderProcess { get; set; }
        public string SKUPriceRetainedDecimal { get; set; }
        public string LocalWareHouseStockUpEstimated { get; set; }
        public string OverseasWareHouseStockUpEstimated { get; set; }
        public string IsChooseForeignCurrencyForOrder { get; set; }
        public string CurrencyId { get; set; }
        public string PaginationPurchaseOrder { get; set; }
        public string IsSingleProductWeight { get; set; }
        public string PickingAndCheckingAtTheSameTime { get; set; }
        public string IsNewest { get; set; }
        public string IsCancelRawMaterialPackage { get; set; }
        public string CorporateName { get; set; }
        public string CompanyAddress { get; set; }
        public string CompanyPhone { get; set; }
        public string IsSingleNumberUnderNote1688 { get; set; }
        public string OrderNotes1688 { get; set; }
        public string IsSupportDistributionPriceList1688 { get; set; }
        public string CustomsClearanceBasePrice { get; set; }
        public string CustomsClearancePriceCurrency { get; set; }
        public string SelectOrderPureTuneLimitedTime { get; set; }
        public string TallyWarehousIds { get; set; }
        public string IsPackageWeighingConditionSetting { get; set; }
        public string PackageWeighingFirstStageType { get; set; }
        public string FirstStagePercentageOverweight { get; set; }
        public string PackageWeighingTwoStageType { get; set; }
        public string TwoStagePercentageOverweight { get; set; }
        public string PackageWeighingThreeStageType { get; set; }
        public string ThreeStagePercentageOverweight { get; set; }
        public string IsChooseDefaultLanguageTranslation { get; set; }
        public string LastCalcProfitsTime { get; set; }
        public string ProductScrapCondition { get; set; }
        public string TimeCondition { get; set; }
        public string TranslationType { get; set; }
        public string IsOtherWareHouseProductIn { get; set; }
        public string IsPurchasePackage { get; set; }
        public string IsEnable1688AutomaticallyOrders { get; set; }
        public string IsEnable1688AutomaticallySubmit { get; set; }
        public string IsShowLocatInvBulidStockOrder { get; set; }
        public string IsSingleRemarks1688 { get; set; }
        public string IsStartLockAmont { get; set; }
        public string LockDay { get; set; }
        public string IsEnableBalanceInventory { get; set; }
        public string ProductStatus { get; set; }
        public string IsFilterTariffFeeShare { get; set; }
        public string IsOneMultiScannAllProductPrint { get; set; }
        public string IsEnableDetailIDPrint { get; set; }
        public string IsEnableBarCodePrintSplit { get; set; }
        public string PackageWarehousIds { get; set; }
        public string IsPackageWeightGenerateBatch { get; set; }
        public string OverseaTransportFilePath { get; set; }
        public string IsHiddenPrintSonSku { get; set; }
        public string AmazonCampaignSource { get; set; }
        public string OverseaApiLink { get; set; }
        public string IsUseApiPlatform { get; set; }
        public string FBABarcodePrintSize { get; set; }
        public string FBABarcodePrintOrderRule { get; set; }
        public string FBABarcodePrintIsShowMadeInChina { get; set; }
        public string FBABarcodePrintRemark { get; set; }
        public string FBABarcodePrintSingleOrDouble { get; set; }
        public string IsCustomPurchaseSet { get; set; }
        public string CustomPurchaseSetID { get; set; }
        public string IsCustomSinglesSet { get; set; }
        public string CustomSinglesSetID { get; set; }
        public string IsCheckTransport { get; set; }
        public string OpenNewInventoryManagementTime { get; set; }
        public string EndNewInventoryManagementTime { get; set; }
        public string IsTitleValid { get; set; }
        public string IsPickingOrderType { get; set; }
        public string CustomPickingOrderStyle { get; set; }
        public string IsSynchronizeStock { get; set; }
        public string IsTurnOnAutoUpdatePurchaseDays { get; set; }
        public string IsPackageMerging { get; set; }
        public string IsOpenGenerateFBARefund { get; set; }
        public string IsLinkYuncang { get; set; }
        public string FilterTariffFeeCountryIds { get; set; }
        public string TaxRefundRate { get; set; }
        public string ReceivdGoods { get; set; }
        public string VatRateType { get; set; }
        public string VatRate { get; set; }
        public string IsCheckPackingBoxingVolumeAndWeight { get; set; }
        public string IsCheckPackingBoxingProductNum { get; set; }
        public string IsCheckPackingBoxingProductSKU { get; set; }
        public string IsCheckPackingBoxingFBA { get; set; }
        public string IsShowLimitedPickingBatch { get; set; }
        public string FilterTariffFeeShareType { get; set; }
        public string ReceivdGoodsType { get; set; }
        public string IsNewPackingBoxingPutInWithOversea { get; set; }
        public string IsOpenGenerateFBAReturn { get; set; }
        public string IsUpdateUseageInventory { get; set; }
        public string IsBatchImportInventory { get; set; }
        public string IsEnableNewCalculator { get; set; }
        public string IsCheckProductCheckStatus { get; set; }
        public string IsProduct1688Push { get; set; }
        public string IsOpenPackageBarcodeSlice { get; set; }
        public string IsEnableDynamicStock { get; set; }
        public string IsOpenMovePosition { get; set; }
        public string IsLoadRecommendSKU { get; set; }
        public string IsAllotMoveTask { get; set; }
        public string IsRemoveRecommendSKU { get; set; }
        public string ShelfMode { get; set; }
        public string WishExchangeRate { get; set; }
        public string IsEnableStockupAnalysisV2ProtectNum { get; set; }
        public string IsEbayAutoSupplementAndInventory { get; set; }
        public string EnableEbayAutoSupplement { get; set; }
        public string EbayListingQty { get; set; }
        public string EbaySupplementaryQty { get; set; }
        public string IsEbayInventoryCheck { get; set; }
        public string EbayCustomInventoryType { get; set; }
        public string EbayCustomInventoryQty { get; set; }
        public string AmazonDescriptionInsertColor { get; set; }
        public string AmazonDescriptionInsertSize { get; set; }
        public string HighRiskwordsInterceptModel { get; set; }
        public string PrintPackingOrderType { get; set; }
        public string IsOpenAutoGenerateEabyRefund { get; set; }
        public string IsUseAmazonProductMultipleInfo { get; set; }
        public string IsOpenOneProductMorePosition { get; set; }
        public string IsEnableTitleLibrary { get; set; }
        public string IsOpenSplitStorage { get; set; }
        public string ImportFirstLegTime { get; set; }
        public string IsEnableEbayProductDetails { get; set; }
        public string IsEnableOrderSourceSkuV2 { get; set; }
        public string RiskwordsSourceType { get; set; }
        public string CheckRelationStockOrderNumber { get; set; }
        public string AliExpHighRiskwordsInterceptModel { get; set; }
        public string EbayHighRiskwordsInterceptModel { get; set; }
        public string WishHighRiskwordsInterceptModel { get; set; }
        public string AliExpRiskwordsSourceType { get; set; }
        public string EbayRiskwordsSourceType { get; set; }
        public string WishRiskwordsSourceType { get; set; }
        public string BatchOrderSourceSkuFetchNum { get; set; }
        public string MaxOrderSourceSkuFetchNum { get; set; }
        public string TranslateMode { get; set; }
        public string IsEnableListingInfoV2 { get; set; }
        public string IsOpenAmazonPII { get; set; }
        public string IsEmbedPermissionSystem { get; set; }
        public string IsOpenTransitBox { get; set; }
        public string IsRemoveOrderLog { get; set; }
        public string IsOpenFactoryDirectDelivery { get; set; }
        public string IsLimitNotDefaultWarehouseRestock { get; set; }
        public string IsPCodeUnderNote1688 { get; set; }
        public string CNAnalysisAlongMonth { get; set; }
        public string IsNewProcurementLoadAnalysis { get; set; }
        public string IsOpenWorkflowPopUP { get; set; }
        public string IsPrintPackagePagination { get; set; }
        public string IsSplitOrderByOversea { get; set; }
        public string IsLocalOrderDefaultWareHouse { get; set; }
        public string ProcurementBuildTime { get; set; }
        public string IsUseProductClassRedisLock { get; set; }
        public string IsTurnOnBrandSearchValueHide { get; set; }
        public string IsRequiredWithBattery { get; set; }
        public string AddressMatch { get; set; }
        public string IsGetProductLogByApi { get; set; }
        public string IsStockOrderEditPermission { get; set; }
        public string IsAmazonFinancialFromDataServer { get; set; }
        public string IsShowLimitedPickingBatchNew { get; set; }
        public string IsOpenCalculateAvgPriceWhenProcessFinishedSKU { get; set; }
        public string IsTransformBrand { get; set; }
        public string IsSyncGroupSkuInfo { get; set; }
        public string IsManagementAccountEnabled { get; set; }
        public string IsStrikeOp { get; set; }
        public string IsShowProductIntellectualIsBrand { get; set; }
        public string IsProductEditMultiAttachment { get; set; }
        public string IsOpenAvgePriceWhenReceiveAllocationDetail { get; set; }
        public string IsOpenNewInterfaceWith1688 { get; set; }
        public string IsMultiTabMainPage { get; set; }
        public string IsProcurementBuildSingle { get; set; }
        public string IsTestTempFunc { get; set; }
        public string IsEnableTaobaoPlaceOrderProcess { get; set; }
    }
}
